import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#F8FAFC',
    zIndex: 999, 
  },
  container: {
    flex: 1,
    padding: 20,
    justifyContent: 'center',
  },
  header: {
    alignItems: 'center',
    marginBottom: 40,
  },
  subTitle: {
    fontSize: 13,
    color: '#94A3B8',
    marginBottom: 10,
    fontWeight: '500',
  },
  titleWrapper: {
    alignItems: 'center',
  },
  // [NEW]: "미니 게임" 작은 텍스트 스타일
  miniTag: {
    fontSize: 14,
    fontWeight: '700',
    color: '#6366F1',
    backgroundColor: '#EEF2FF',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 8,
    overflow: 'hidden',
    marginBottom: 6,
  },
  mainTitle: {
    fontSize: 28, // 크기 키움
    fontWeight: '900',
    color: '#1E293B',
    textAlign: 'center',
  },
  gameArea: {
    alignItems: 'center',
    width: '100%', 
  },
  cardWrapper: {
    width: '100%',
    alignItems: 'center',
  },
  roundText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#64748B',
    marginBottom: 20,
  },
  cardA: {
    width: '100%',
    height: 120,
    backgroundColor: '#EEF2FF',
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    borderWidth: 2,
    borderColor: '#C7D2FE',
  },
  cardB: {
    width: '100%',
    height: 120,
    backgroundColor: '#FFF1F2',
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    borderWidth: 2,
    borderColor: '#FECDD3',
  },
  cardText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#334155',
    textAlign: 'center',
  },
  vsText: {
    fontSize: 22,
    fontWeight: '900',
    color: '#CBD5E1',
    marginVertical: 15,
  },
  resultArea: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EEF2FF', 
    borderRadius: 40,
    marginHorizontal: 10,
    paddingVertical: 50,
    shadowColor: "#6366F1",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 5,
  },
  menuNameContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: 160,
    marginBottom: 10,
  },
  gameResultTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#6366F1',
    marginBottom: 8,
    zIndex: 2,
  },
  lottieAnimation: {
    position: 'absolute',
    width: 450,  
    height: 450,
    zIndex: 0,
  },
  resultMenuText: {
    fontSize: 42,
    fontWeight: '900',
    color: '#312E81',
    zIndex: 2,
  },
  resultSubText: {
    fontSize: 16,
    color: '#475569',
    textAlign: 'center',
    lineHeight: 24,
    fontWeight: '600',
    zIndex: 2,
    marginTop: 15,
  },
  promptArea: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  promptTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#1E293B',
    marginTop: 20,
    marginBottom: 10,
  },
  promptSub: {
    fontSize: 15,
    color: '#64748B',
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 40,
  },
  btnRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    gap: 12,
  },
  declineBtn: {
    flex: 1,
    height: 52,
    backgroundColor: '#F1F5F9',
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  acceptBtn: {
    flex: 1,
    height: 52,
    backgroundColor: '#6366F1',
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 2,
  },
  declineBtnText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#64748B',
  },
  acceptBtnText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  standardLoadingArea: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  standardLoadingText: {
    marginTop: 20,
    fontSize: 16,
    fontWeight: '600',
    color: '#64748B',
    textAlign: 'center',
    lineHeight: 24,
  }
});